"""永続化 Repository の Protocol 定義（ADR-001）。"""
from __future__ import annotations

from typing import Any, Optional, Protocol

from core.utils.watchlist_io import PositionEntry, WatchlistItem


class WatchlistRepository(Protocol):
    def load_all(self) -> list[WatchlistItem]: ...
    def save_all(self, items: list[WatchlistItem]) -> None: ...
    def get_positions(self) -> dict[str, PositionEntry]: ...


class PortfolioRepository(Protocol):
    def get_cash_yen(self) -> int: ...
    def set_cash_yen(self, cash_yen: int | float) -> None: ...


class DailyReportRepository(Protocol):
    def get_last(self) -> Optional[dict[str, Any]]: ...
    def get_previous(self) -> Optional[dict[str, Any]]: ...
    def save_last(self, report: dict[str, Any]) -> None: ...
    def save_previous(self, report: dict[str, Any]) -> None: ...
    def rotate_previous(self, new_last: dict[str, Any]) -> None: ...
    def save_last_with_date_rotation(self, new_report: dict[str, Any]) -> None: ...


class ScoreHistoryRepository(Protocol):
    def load_all(self) -> dict[str, Any]: ...
    def save_all(self, history: dict[str, Any]) -> None: ...
    def get_day(self, logical_date: str) -> dict[str, Any]: ...
    def upsert_day(self, logical_date: str, ticker_scores: dict[str, dict[str, Any]]) -> dict[str, Any]: ...


class RunJobRepository(Protocol):
    def get_status(self) -> dict[str, Any]: ...
    def update_status(
        self,
        status: str,
        message: str,
        step: Optional[int] = None,
        total_steps: int = 7,
        finished_at: Optional[str] = None,
    ) -> None: ...


class MarketCacheRepository(Protocol):
    def load(self) -> Optional[dict[str, Any]]: ...
    def save(self, data: dict[str, Any]) -> None: ...


class SectorPeersRepository(Protocol):
    def load(self) -> dict[str, Any]: ...
    def save(self, data: dict[str, Any]) -> None: ...


class TickerAnalysisRepository(Protocol):
    def get(self, ticker: str) -> Optional[dict[str, Any]]: ...
    def save(self, ticker: str, payload: dict[str, Any]) -> None: ...
    def list_tickers(self) -> list[str]: ...
